version: '3.4'
services:
  confluence:
    image: kutim/confluence:7.3.1
    container_name: confluence
    environment:
      - TZ='Asia/Shanghai'
      - JVM_MINIMUM_MEMORY=1g
      - JVM_MAXIMUM_MEMORY=12g
      - JVM_CODE_CACHE_ARGS='-XX:InitialCodeCacheSize=1g -XX:ReservedCodeCacheSize=8g'
    depends_on:
      - db
    ports:
      - "8090:8090"
    volumes:
      - /root/confluence_data:/var/confluence
    restart: always
    networks:
      - network-bridge

  db:
    image: kutim/postgres:9.6.17
    container_name: confluence-db
    environment:
      - TZ='Asia/Shanghai'
      - POSTGRES_USER=postgres
      - POSTGRES_DB=confluence
      - POSTGRES_PASSWORD=654321
#    ports:
#      - "5432"
    volumes:
      - /root/confluence-db_data:/var/lib/postgresql/data
    restart: always
    networks:
      - network-bridge

networks:
  network-bridge:
    driver: bridge
